In [26]:
import time
import psycopg2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances
from geopy.geocoders import Nominatim
from sqlalchemy import create_engine

In [74]:
full_df = pd.read_csv("umn_apartment_data.csv") #reading csv file

#spliting dataframes between amenities and other data points
df = full_df.iloc[:,:]
amenities_df = full_df.iloc[:,9:]

#loop through all amenities to put into 1 list
temp_df = pd.DataFrame()
for index, values in amenities_df.iterrows():
    my_list = [values.unique()[:-1]]
    temp_df = pd.concat([temp_df, pd.Series(my_list)], ignore_index = True) #adding list into dataframe in each iteration

#recombining main df with modified amenities df
df = pd.concat([df, temp_df], axis = 1, ignore_index = True)

#renaming columns
column_list = ["Name", "Floor Plan", "Address", "Bedrooms", "Bathrooms", "Price", "Size", "Availability", "Link", "Amenities", "AmenitiesID"]
column_dic = {}
for i in range(len(column_list)):
    column_dic[df.columns.values[i]] = column_list[i]

df = df.rename(columns = column_dic)

Potential Features:
- Location (Distance from a Central Point)
- Amount of Bathrooms/Beds
- Price
- Size
- Amenities (Specific ID for Each Kind)
- Shaping (potentially)

In [75]:
#replacing each value in Bedrooms column with numerical value
idx = 0
for value in df["Bedrooms"]:
    if value == "Studio":
        df.iloc[idx, 3] = "0"
    else:
        df.iloc[idx, 3] = value[0]
    idx += 1

#replacing each value in Price column with numerical value
idx = 0
for value in df["Price"]:
    end_id = value.find("-")
    try:
        df.iloc[idx, 5] = pd.to_numeric(value[1:end_id])
    except:
        df.iloc[idx, 5] = None
    idx += 1

# if price is not divided for each indivudal, do it manually
ids = df[df["Price"] > 2000].index
for id in ids:
    df.iloc[id, 5] /= pd.to_numeric(df.iloc[id, 3])


#replacing each value in Size column with numerical value
# idx = 0
# for value in df["Size"]:
#     if type(value) is str:
#         end_id = value.find("-") + 1
#     try:
#         df.iloc[idx, 6] = pd.to_numeric(value[1:end_id])
#     except:
#         df.iloc[idx, 6] = None
#     idx += 1


#making each value numeric - if error occurs replaces value with NaN
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Size'] = pd.to_numeric(df['Size'], errors='coerce')
df['Bathrooms'] = pd.to_numeric(df['Bathrooms'], errors='coerce')
df['Bedrooms'] = pd.to_numeric(df['Bedrooms'], errors='coerce')

df = df.dropna().reset_index(drop = True) #removing all none types

In [39]:
df.iloc[45, 5] / pd.to_numeric(df.iloc[45, 3])

np.float64(761.25)

In [4]:
print(df[["Price", "Size", "Bathrooms", "Bedrooms"]].corr()) #correlation square

              Price      Size  Bathrooms  Bedrooms
Price      1.000000  0.642045   0.411153  0.531827
Size       0.642045  1.000000   0.623007  0.676832
Bathrooms  0.411153  0.623007   1.000000  0.723046
Bedrooms   0.531827  0.676832   0.723046  1.000000

In [ ]:
full_house_df = pd.read_csv("umn_housing_data.csv") #reading csv

In [4]:
#spliting dataframes between amenities and other data points
house_df = full_house_df.iloc[:,:7]
house_amenities_df = full_house_df.iloc[:,7:]
house_amenities_df

#loop through all amenities to put into 1 list
temp_df = pd.DataFrame()
for index, values in house_amenities_df.iterrows():
    my_list = [values.unique()[:-1]]
    temp_df = pd.concat([temp_df, pd.Series(my_list)], ignore_index = True)

#recombining main df with modified amenities df
house_df = pd.concat([house_df, temp_df], axis = 1, ignore_index = True)

#naming columns
column_list = ["Address", "Name", "Bedrooms", "Bathrooms", "Price", "Size", "Availability", "Amenities"]
column_dic = {}
for i in range(len(column_list)):
    column_dic[house_df.columns.values[i]] = column_list[i]

house_df = house_df.rename(columns = column_dic)
house_df #outputs dataframe

NameError: name 'full_house_df' is not defined

In [ ]:
#creates all values in Price column numeric
idx = 0
for value in house_df["Price"]:
    end_id = value.find("-")
    try:
        house_df.iloc[idx, 4] = pd.to_numeric(value[1:end_id])
    except:
        house_df.iloc[idx, 4] = None
    idx += 1

In [4]:
df[['Bedrooms', 'Bathrooms', 'Size', 'Price']]

     Bedrooms  Bathrooms    Size   Price
0           4        4.0  1239.0   599.0
1           4        4.0  1239.0   639.0
2           3        3.0  1035.0   669.0
3           3        3.0  1035.0   719.0
4           2        2.0   806.0   849.0
..        ...        ...     ...     ...
414         2        1.0   743.0  1425.0
415         5        2.0  2600.0  3295.0
416         5        4.0  1600.0  3295.0
417         5        4.0     0.0  3095.0
418         4        2.0  1400.0  2795.0

[419 rows x 4 columns]

Alternatives to Cosine Similarity:
- Euclidean Distance
- Dot Product

In [4]:
id = 0 #choosing the id of the apartment you want to find recommendations for
req = df.iloc[id,3] #grabbing # of bedrooms in given id

#defining df of all numeric values that has the same amount of bedrooms as a given id
cdf = df[df['Bedrooms'] == req].copy() 
cdf = cdf[['Bedrooms', 'Bathrooms', 'Size', 'Price']]

#adding weights to each option
cdf["Bathrooms"] *= 1.5
cdf["Price"] /= 500
cdf["Size"] /= 1000

#calculating cosine similarity
user_similarity = cosine_similarity(cdf)

#finding similar apartments to given id
apartment_id = cdf.index.get_loc(id)
similar_apartments = user_similarity[id]

similar_apartments_indices = np.argsort(similar_apartments)[::-1][1:6] #shows best 5 similar apartments (ignoring the apartment itself)
similar_apartments = cdf.index[similar_apartments_indices] #grabbing indexes of similar apartments

df.loc[similar_apartments]

,Name,Floor Plan,Address,Bedrooms,Bathrooms,Price,Size,Availability,Link,Amenities,AmenitiesID
1,The Quad on Delaware,D1R - Renovated 4 Bedroom 4 Bath,2508 Delaware Street SE Minneapolis MN 55414,4,4.0,639.0,1239.0,08-27-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Garbage Disposal, Parking Available, 24 Hour E...",[]
38,The Knoll Dinkytown,D1,1101 University Ave SE Minneapolis MN 55414,4,4.0,955.0,1596.0,08-19-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Custom Tile Backsplash, Furnished, Granite Cou...",[]
51,The Bridges Dinkytown,D1,930 University Ave SE Minneapolis MN 55414,4,4.0,955.0,1626.0,08-21-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Custom Tile Backsplash, Furnished, Granite Cou...",[]
39,The Knoll Dinkytown,D3,1101 University Ave SE Minneapolis MN 55414,4,4.0,975.0,1657.0,08-19-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Custom Tile Backsplash, Furnished, Granite Cou...",[]
168,Factory Lofts,4 Bedroom - Individual Bedroom,2655 Essex St SE Minneapolis MN 55414 USA,4,4.0,694.0,300.0,Now,https://listings.umn.edu/city/minneapolis-mn/l...,"14 Foot Ceilings, Air Conditioning, Ample Clos...",[]

In [9]:
id = 0 #choosing the id of the apartment you want to find recommendations for
req = df.iloc[id,3] #grabbing # of bedrooms in given id

#defining df of all numeric values that has the same amount of bedrooms as a given id
edf = df[df['Bedrooms'] == req].copy().drop_duplicates("Address")
edf = edf[['Address', 'Bedrooms', 'Bathrooms', 'Size', 'Price']]

geolocator = Nominatim(user_agent="apartment-finder") 

central_address = "207 Church Street SE, Minneapolis, MN 55455" #Lind Hall
central_location = geolocator.geocode(central_address) #grabs location

address_list = []

lat_list = []
long_list = []

for address in edf["Address"]:
    time.sleep(1) #Nominatim allow max 1 inquiry per second, prevents timeout error
    #can use a rotating api key to bypass rate limit - but need something that uses api keys
    
    #if address is not already used grab the coordinates of the address
    if address not in address_list: 
        location = geolocator.geocode(address)
        address_list.append(address) #to check if it has been used
        
    try:
        lat_list.append(location.latitude)
        long_list.append(location.longitude)
    except (AttributeError): #will edit later
        lat_list.append(-1)
        long_list.append(-1)

distance_list = []

for i in range(len(lat_list)):
    distance = ((central_location.latitude - lat_list[i])**2 + (central_location.latitude - lat_list[i])**2)**0.5 #calculating distance between Lind Hall and given apartment
    distance_list.append(distance * 10**5 * 1.11 / 1609.34) #distance in miles

cdf = pd.concat([edf.reset_index(), pd.Series(lat_list), pd.Series(long_list), pd.Series(distance_list)], axis=1)

cdf = cdf[["index", "Bedrooms", "Bathrooms", "Size", "Price", 2]]
cdf.columns.values[-1] = "Distance"

# #adding weights to each option
# cdf["Bathrooms"] *= 1.5
# cdf["Price"] /= 500
# cdf["Size"] /= 1000
# cdf["Distance"] *= 2

In [10]:
test = cdf.copy()

In [11]:
rdf = test.copy()

rdf["Bathrooms"] *= 5
rdf["Price"] /= 25
rdf["Size"] /= 500
rdf["Distance"] *= 40

#calculating cosine similarity
user_similarity = euclidean_distances(rdf[["Bedrooms", "Bathrooms", "Size", "Price", "Distance"]])

In [14]:
columns = ' FLOAT, '.join([str(i) for i in range(len(user_similarity[0] ))])

In [72]:
rdf = test.copy()

rdf["Bathrooms"] *= 5
rdf["Price"] /= 25
rdf["Size"] /= 500
rdf["Distance"] *= 40

#calculating cosine similarity
user_similarity = euclidean_distances(rdf[["Bedrooms", "Bathrooms", "Size", "Price", "Distance"]])

#finding similar apartments to given id
apartment_id = rdf.index.get_loc(id)
similar_apartments = user_similarity[id]

similar_apartments_indices = np.argsort(similar_apartments)[1:] #shows best 5 similar apartments (ignoring the apartment itself)
similar_apartments = cdf.index[similar_apartments_indices] #grabbing indexes of similar apartments

df.loc[rdf.loc[similar_apartments]["index"]]

,Name,Floor Plan,Address,Bedrooms,Bathrooms,Price,Size,Availability,Link,Amenities,AmenitiesID
166,Factory Lofts,4 Bedroom,2655 Essex St SE Minneapolis MN 55414 USA,4,4.0,687.50,1999.0,08-21-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"14 Foot Ceilings, Air Conditioning, Ample Clos...",[]
353,Thomas Place,4 Bedroom,624 University Ave SE. Minneapolis MN 55414,4,2.0,635.00,1200.0,09-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"9 Foot Ceilings, Air Conditioning, Ample Close...",[]
418,2622 Essex,#101,2622 Essex St SE Minneapolis MN 55414 USA,4,2.0,698.75,1400.0,09-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"9 Foot Ceilings, Air Conditioning, Ample Close...",[]
386,Tairrie House,J,609 SE Oak St Minneapolis MN 55414,4,2.0,694.00,1280.0,08-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Air Conditioning, Bay Windows, Dishwasher, Gar...",[]
74,University Village,C - Private Bedroom,2515 University Ave SE Minneapolis MN 55414,4,2.0,750.00,1261.0,Now,https://listings.umn.edu/city/minneapolis-mn/l...,"Air Conditioning, Ample Closet Space, Carpet, ...",[]
51,The Bridges Dinkytown,D1,930 University Ave SE Minneapolis MN 55414,4,4.0,955.00,1626.0,08-21-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Custom Tile Backsplash, Furnished, Granite Cou...",[]
38,The Knoll Dinkytown,D1,1101 University Ave SE Minneapolis MN 55414,4,4.0,955.00,1596.0,08-19-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Custom Tile Backsplash, Furnished, Granite Cou...",[]
6,Doyle Apartments,707,1307 4th Street SE Minneapolis MN 55414 USA,4,2.0,795.00,1192.0,08-25-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"9 Foot Ceilings, Air Conditioning, Bedrooms Ke...",[]
93,Golden Lodge,The Swede,621 15th Ave SE Minneapolis MN 55414,4,3.0,695.00,1600.0,09-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Air Conditioning, Bedrooms Keyed Separately, B...",[]
102,Chateau Student Housing Cooperative,907,425 13th Ave SE Minneapolis MN 55414 USA,4,2.0,611.25,1100.0,Now,https://listings.umn.edu/city/minneapolis-mn/l...,"Air Conditioning, Ample Closet Space, Bedrooms...",[]
19,Bierman Place,The Quad - By-the-bed,1401 6th Street SE Minneapolis MN 55414 USA,4,2.0,650.00,0.0,Call for Availability,https://listings.umn.edu/city/minneapolis-mn/l...,"Bedrooms Keyed Separately, Breakfast Bar, Dish...",[]
26,525 Tenth Apartments Dinkytown,Unit 205,525 10th Ave SE Minneapolis MN 55414 USA,4,2.0,699.00,1282.0,08-31-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"9 Foot Ceilings, Air Conditioning, Ample Close...",[]
226,Cluster: 1011 & 1015 4th St SE,#203,1011 & 1015 4th St SE Minneapolis MN 55414 USA,4,2.0,698.75,1400.0,08-23-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Dishwasher, Keyless Entry, Microwave, Oven, Re...",[]
358,917/919 22nd Ave SE,917 22nd Ave SE,917 22nd Ave SE Minneapolis MN 55414 USA,4,2.0,550.00,0.0,09-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Oven, Refrigerator",[]
163,501 6th St SE,#201,501 6th St SE Minneapolis MN 55414 USA,4,2.0,637.50,1600.0,09-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Air Conditioning, Den, Dishwasher, Fresh Paint...",[]
28,Spectrum Apartments & Townhomes,809-8,815 SE 9th Ave Minneapolis MN 55414 USA,4,4.0,723.75,1715.0,06-05-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"9 Foot Ceilings, Air Conditioning, Bedrooms Ke...",[]
345,403 6th St SE,1,403 6th St SE Minneapolis MN 55414 USA,4,2.0,562.50,1300.0,Call for Availability,https://listings.umn.edu/city/minneapolis-mn/l...,"Dishwasher, Hardwood Floors, Oven, Quartz Coun...",[]
396,Bookend on Campus,Book 4,807 4th St SE Minneapolis MN 55414 USA,4,1.5,1795.00,997.0,Now,https://listings.umn.edu/city/minneapolis-mn/l...,"Ample Closet Space, 24 Hour Emergency Maintena...",[]
357,1203 Como Ave SE,#1,1203 Como Ave SE Minneapolis MN 55414 USA,4,2.5,623.75,1800.0,09-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Oven, Pantry, Private Bathrooms, Refrigerator,...",[]

In [71]:
test

    index  Bedrooms  Bathrooms    Size    Price     Distance
0       0         4        4.0  1239.0   599.00     0.283544
1       6         4        2.0  1192.0   795.00     0.642409
2      19         4        2.0     0.0   650.00     0.787015
3      26         4        2.0  1282.0   699.00     0.925963
4      28         4        4.0  1715.0   723.75     1.305585
5      38         4        4.0  1596.0   955.00     0.509519
6      51         4        4.0  1626.0   955.00     0.328998
7      74         4        2.0  1261.0   750.00     0.110173
8      93         4        3.0  1600.0   695.00     0.749149
9     102         4        2.0  1100.0   611.25     0.720189
10    163         4        2.0  1600.0   637.50     1.262735
11    166         4        4.0  1999.0   687.50     0.374745
12    226         4        2.0  1400.0   698.75     1.126265
13    345         4        2.0  1300.0   562.50     1.323562
14    353         4        2.0  1200.0   635.00     0.328998
15    357         4        2.5  1800.0   623.75  4484.431040
16    358         4        2.0     0.0   550.00     1.230810
17    386         4        2.0  1280.0   694.00     0.454047
18    396         4        1.5   997.0  1795.00     0.904767
19    418         4        2.0  1400.0   698.75     0.406232

In [66]:
print(user_similarity[0,-1])

418.16755912006863

In [71]:
engine = create_engine('postgresql://postgres:1Oscar2006@localhost:5432/oscar')

In [73]:
user_similarity = pd.read_sql_table('recommendations', con=engine)
user_similarity

,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,...,col409,col410,col411,col412,col413,col414,col415,col416,col417,col418
0,0.000000,1.600000,5.831506,7.014732,14.309086,15.771809,19.171062,20.170866,21.096441,22.333357,...,45.463294,45.463572,45.465702,35.573917,58.157861,112.701807,34.935806,5.675813,5.719620,11.872546
1,1.600000,0.000000,5.254185,6.033777,13.240467,14.591434,18.574219,19.424104,20.245786,21.378748,...,43.989443,43.989731,43.991932,34.149313,57.742608,112.243171,34.862451,5.205272,5.719620,11.434569
2,5.831506,5.254185,0.000000,2.000000,8.834578,10.528521,16.048531,16.869432,17.692448,18.786617,...,41.308977,41.309204,41.310955,31.092353,56.289562,111.336743,33.842254,7.441134,7.887869,7.272041
3,7.014732,6.033777,2.000000,0.000000,7.297244,8.834578,15.536903,16.112658,16.764925,17.685501,...,39.416133,39.416371,39.418207,29.233104,55.860136,110.810245,33.924890,7.808359,8.615014,7.219597
4,14.309086,13.240467,8.834578,7.297244,0.000000,2.000000,14.673675,14.514417,14.627653,14.899594,...,33.360627,33.360798,33.362144,22.900926,54.331391,109.251678,34.437987,13.936116,14.871857,8.152608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,112.701807,112.243171,111.336743,110.810245,109.251678,108.847458,95.855857,95.301224,94.894670,94.437618,...,114.755634,114.755675,114.756000,101.954161,55.694010,0.000000,79.852802,107.309816,107.774185,105.897490
415,34.935806,34.862451,33.842254,33.924890,34.437987,34.933866,19.899783,20.608764,21.311746,22.410628,...,57.577987,57.578585,57.583103,41.540290,25.826568,79.852802,0.000000,30.051621,30.474578,28.432165
416,5.675813,5.205272,7.441134,7.808359,13.936116,15.120030,14.795027,15.736982,16.654188,17.994880,...,44.550964,44.551377,44.554523,33.203499,53.026157,107.309816,30.051621,0.000000,3.577709,10.182735
417,5.719620,5.719620,7.887869,8.615014,14.871857,16.185553,15.616607,16.725495,17.760506,19.128567,...,45.930395,45.930238,45.929110,34.657760,53.424164,107.774185,30.474578,3.577709,0.000000,10.909450
418,11.872546,11.434569,7.272041,7.219597,8.152608,9.721369,10.130593,11.153506,12.189876,13.645856,...,40.628931,40.629306,40.632165,28.381354,50.606741,105.897490,28.432165,10.182735,10.909450,0.000000

In [76]:
index = 0
df

,Name,Floor Plan,Address,Bedrooms,Bathrooms,Price,Size,Availability,Link,Amenities,AmenitiesID
0,The Quad on Delaware,D1 - 4 Bedroom 4 Bath,2508 Delaware Street SE Minneapolis MN 55414,4,4.0,599.00,1239.0,08-27-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Garbage Disposal, Parking Available, 24 Hour E...",[]
1,The Quad on Delaware,D1R - Renovated 4 Bedroom 4 Bath,2508 Delaware Street SE Minneapolis MN 55414,4,4.0,639.00,1239.0,08-27-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Garbage Disposal, Parking Available, 24 Hour E...",[]
2,The Quad on Delaware,C1 - 3 Bedroom 3 Bath,2508 Delaware Street SE Minneapolis MN 55414,3,3.0,669.00,1035.0,08-27-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Garbage Disposal, Parking Available, 24 Hour E...",[]
3,The Quad on Delaware,C1R - Renovated 3 Bedroom 3 Bath,2508 Delaware Street SE Minneapolis MN 55414,3,3.0,719.00,1035.0,08-27-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Garbage Disposal, Parking Available, 24 Hour E...",[]
4,The Quad on Delaware,B1 - 2 Bedroom 2 Bath,2508 Delaware Street SE Minneapolis MN 55414,2,2.0,849.00,806.0,08-27-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Garbage Disposal, Parking Available, 24 Hour E...",[]
...,...,...,...,...,...,...,...,...,...,...,...
414,1621 Taylor St NE,#9,1621 Taylor St NE Minneapolis MN 55413 USA,2,1.0,1425.00,743.0,Now,https://listings.umn.edu/city/minneapolis-mn/l...,"Oven, Parking Available, Refrigerator, Cats, Dogs",[]
415,879 23rd Ave SE,#1,879 23rd Ave SE Minneapolis MN 55414 USA,5,2.0,659.00,2600.0,09-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"Oven, Refrigerator",[]
416,2622 Essex,#401,2622 Essex St SE Minneapolis MN 55414 USA,5,4.0,659.00,1600.0,09-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"9 Foot Ceilings, Air Conditioning, Ample Close...",[]
417,2622 Essex,#301,2622 Essex St SE Minneapolis MN 55414 USA,5,4.0,619.00,0.0,09-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"9 Foot Ceilings, Air Conditioning, Ample Close...",[]
418,2622 Essex,#101,2622 Essex St SE Minneapolis MN 55414 USA,4,2.0,698.75,1400.0,09-01-2026,https://listings.umn.edu/city/minneapolis-mn/l...,"9 Foot Ceilings, Air Conditioning, Ample Close...",[]

In [ ]:
bedrooms = df.iloc[index,4]
filtered_df = df[df["Bedrooms"] == bedrooms].drop_duplicates("Name")

array([  0,   6,  19,  26,  28,  38,  51,  74,  93, 102, 163, 166, 226,
       345, 353, 357, 358, 386, 396, 418])

In [ ]:
similar_apartments = user_similarity.iloc[index,filtered_df.index.values]
ordered_apartments = similar_apartments.sort_values()[1:]
id_list = []
for key, val in ordered_apartments.items():
    id_list.append(int(key[3:]))
id_list
df.iloc[id_list, :]